/**
 * mockAdmin.ts — Datos de ejemplo para previsualizar el panel de administración.
 * Se usan automáticamente cuando no hay contexto WordPress disponible (desarrollo sin WP).
 * En producción/WP real, el hook usa los datos del API y estos no se cargan.
 */

import type {
    AdminReserva,
    AdminCliente,
    AdminVehiculoEditable,
    AdminEstadisticas,
} from '@app/types/cresta';

export const MOCK_ESTADISTICAS: AdminEstadisticas = {
    totalReservas: 47,
    reservasConfirmadas: 31,
    reservasPendientes: 8,
    ingresosMes: 4820,
    ingresosTotales: 28650,
    vehiculosActivos: 3,
    clientesUnicos: 34,
};

export const MOCK_RESERVAS: AdminReserva[] = [
    {
        id: 101,
        estado: 'confirmada',
        fechaInicio: '2026-03-10',
        fechaFin: '2026-03-17',
        noches: 7,
        precioTotal: 1050,
        nombreCliente: 'Laura Sánchez',
        emailCliente: 'laura.sanchez@gmail.com',
        telefono: '+34 612 345 678',
        vehiculoNombre: 'Cresta One',
        vehiculoId: 1,
        fechaCreacion: '2026-02-15',
    },
    {
        id: 102,
        estado: 'pendiente',
        fechaInicio: '2026-03-20',
        fechaFin: '2026-03-25',
        noches: 5,
        precioTotal: 750,
        nombreCliente: 'Miguel Torres',
        emailCliente: 'miguel.torres@hotmail.com',
        telefono: '+34 698 123 456',
        vehiculoNombre: 'Cresta One',
        vehiculoId: 1,
        fechaCreacion: '2026-03-01',
    },
    {
        id: 103,
        estado: 'completada',
        fechaInicio: '2026-02-01',
        fechaFin: '2026-02-08',
        noches: 7,
        precioTotal: 980,
        nombreCliente: 'Ana García',
        emailCliente: 'ana.garcia@outlook.es',
        telefono: '+34 655 987 321',
        vehiculoNombre: 'Cresta One',
        vehiculoId: 1,
        fechaCreacion: '2026-01-20',
    },
    {
        id: 104,
        estado: 'pendiente',
        fechaInicio: '2026-04-05',
        fechaFin: '2026-04-12',
        noches: 7,
        precioTotal: 1190,
        nombreCliente: 'Carlos Ruiz',
        emailCliente: 'c.ruiz@empresa.com',
        telefono: '+34 607 654 321',
        vehiculoNombre: 'Cresta One',
        vehiculoId: 1,
        fechaCreacion: '2026-03-04',
    },
    {
        id: 105,
        estado: 'cancelada',
        fechaInicio: '2026-03-01',
        fechaFin: '2026-03-04',
        noches: 3,
        precioTotal: 390,
        nombreCliente: 'Isabel Martínez',
        emailCliente: 'isa.martinez@gmail.com',
        telefono: '+34 633 111 222',
        vehiculoNombre: 'Cresta One',
        vehiculoId: 1,
        fechaCreacion: '2026-02-10',
    },
    {
        id: 106,
        estado: 'confirmada',
        fechaInicio: '2026-04-15',
        fechaFin: '2026-04-22',
        noches: 7,
        precioTotal: 1120,
        nombreCliente: 'Javier López',
        emailCliente: 'javier.lopez@icloud.com',
        telefono: '+34 622 876 543',
        vehiculoNombre: 'Cresta One',
        vehiculoId: 1,
        fechaCreacion: '2026-03-05',
    },
];

export const MOCK_CLIENTES: AdminCliente[] = [
    {
        email: 'laura.sanchez@gmail.com',
        nombre: 'Laura Sánchez',
        telefono: '+34 612 345 678',
        totalReservas: 3,
        ultimaReserva: '2026-03-10',
        gastoTotal: 3150,
    },
    {
        email: 'ana.garcia@outlook.es',
        nombre: 'Ana García',
        telefono: '+34 655 987 321',
        totalReservas: 2,
        ultimaReserva: '2026-02-01',
        gastoTotal: 1820,
    },
    {
        email: 'miguel.torres@hotmail.com',
        nombre: 'Miguel Torres',
        telefono: '+34 698 123 456',
        totalReservas: 1,
        ultimaReserva: '2026-03-20',
        gastoTotal: 750,
    },
    {
        email: 'javier.lopez@icloud.com',
        nombre: 'Javier López',
        telefono: '+34 622 876 543',
        totalReservas: 4,
        ultimaReserva: '2026-04-15',
        gastoTotal: 4480,
    },
    {
        email: 'c.ruiz@empresa.com',
        nombre: 'Carlos Ruiz',
        telefono: '+34 607 654 321',
        totalReservas: 1,
        ultimaReserva: '2026-04-05',
        gastoTotal: 1190,
    },
    {
        email: 'isa.martinez@gmail.com',
        nombre: 'Isabel Martínez',
        telefono: '+34 633 111 222',
        totalReservas: 2,
        ultimaReserva: '2026-03-01',
        gastoTotal: 820,
    },
];

export const MOCK_VEHICULOS: AdminVehiculoEditable[] = [
    {
        id: 1,
        nombre: 'Cresta One',
        descripcionCorta: 'Furgoneta camper para 2 personas, totalmente equipada',
        capacidad: 2,
        plazasViaje: 2,
        combustible: 'diesel',
        transmision: 'manual',
        precioBase: 150,
        activo: true,
        ubicacion: 'Madrid',
        fianza: 500,
        kmIncluidos: 0,
        edadMinima: 21,
        equipamiento: ['cocina', 'nevera', 'ducha', 'panel solar', 'calefaccion'],
        imagen: '',
    },
];
