/**
 * mockAdmin.ts — Datos de ejemplo para previsualizar el panel de administración.
 * Se usan automáticamente cuando no hay contexto WordPress disponible (desarrollo sin WP).
 * En producción/WP real, el hook usa los datos del API y estos no se cargan.
 */

import type {
    AdminReserva,
    AdminCliente,
    AdminVehiculoEditable,
    AdminEstadisticas,
    EventoActividad,
} from '@app/types/cresta';

export const MOCK_ESTADISTICAS: AdminEstadisticas = {
    totalReservas: 47,
    reservasConfirmadas: 31,
    reservasPendientes: 8,
    ingresosMes: 4820,
    ingresosTotales: 28650,
    vehiculosActivos: 3,
    clientesUnicos: 34,
};

export const MOCK_RESERVAS: AdminReserva[] = [
    {
        id: 101,
        estado: 'confirmada',
        fechaInicio: '2026-03-10',
        fechaFin: '2026-03-17',
        noches: 7,
        precioTotal: 1050,
        precioNoche: 150,
        nombreCliente: 'Laura Sanchez',
        emailCliente: 'laura.sanchez@gmail.com',
        telefono: '+34 612 345 678',
        vehiculoNombre: 'Cresta One',
        vehiculoId: 1,
        temporada: 'media',
        notas: '',
        stripeSessionId: 'cs_test_a1b2c3d4',
        fechaCreacion: '2026-02-15',
    },
    {
        id: 102,
        estado: 'pendiente',
        fechaInicio: '2026-03-20',
        fechaFin: '2026-03-25',
        noches: 5,
        precioTotal: 750,
        precioNoche: 150,
        nombreCliente: 'Miguel Torres',
        emailCliente: 'miguel.torres@hotmail.com',
        telefono: '+34 698 123 456',
        vehiculoNombre: 'Cresta One',
        vehiculoId: 1,
        temporada: 'media',
        notas: 'Llegamos sobre las 17h',
        stripeSessionId: 'cs_test_e5f6g7h8',
        fechaCreacion: '2026-03-01',
    },
    {
        id: 103,
        estado: 'completada',
        fechaInicio: '2026-02-01',
        fechaFin: '2026-02-08',
        noches: 7,
        precioTotal: 980,
        precioNoche: 140,
        nombreCliente: 'Ana Garcia',
        emailCliente: 'ana.garcia@outlook.es',
        telefono: '+34 655 987 321',
        vehiculoNombre: 'Cresta One',
        vehiculoId: 1,
        temporada: 'baja',
        notas: '',
        stripeSessionId: 'cs_test_i9j0k1l2',
        fechaCreacion: '2026-01-20',
    },
    {
        id: 104,
        estado: 'pendiente',
        fechaInicio: '2026-04-05',
        fechaFin: '2026-04-12',
        noches: 7,
        precioTotal: 1190,
        precioNoche: 170,
        nombreCliente: 'Carlos Ruiz',
        emailCliente: 'c.ruiz@empresa.com',
        telefono: '+34 607 654 321',
        vehiculoNombre: 'Cresta One',
        vehiculoId: 1,
        temporada: 'alta',
        notas: 'Necesitamos silla de bebe',
        stripeSessionId: 'cs_test_m3n4o5p6',
        fechaCreacion: '2026-03-04',
    },
    {
        id: 105,
        estado: 'cancelada',
        fechaInicio: '2026-03-01',
        fechaFin: '2026-03-04',
        noches: 3,
        precioTotal: 390,
        precioNoche: 130,
        nombreCliente: 'Isabel Martinez',
        emailCliente: 'isa.martinez@gmail.com',
        telefono: '+34 633 111 222',
        vehiculoNombre: 'Cresta One',
        vehiculoId: 1,
        temporada: 'media',
        notas: '',
        stripeSessionId: '',
        fechaCreacion: '2026-02-10',
    },
    {
        id: 106,
        estado: 'confirmada',
        fechaInicio: '2026-04-15',
        fechaFin: '2026-04-22',
        noches: 7,
        precioTotal: 1120,
        precioNoche: 160,
        nombreCliente: 'Javier Lopez',
        emailCliente: 'javier.lopez@icloud.com',
        telefono: '+34 622 876 543',
        vehiculoNombre: 'Cresta One',
        vehiculoId: 1,
        temporada: 'alta',
        notas: '',
        stripeSessionId: 'cs_test_q7r8s9t0',
        fechaCreacion: '2026-03-05',
    },
];

export const MOCK_CLIENTES: AdminCliente[] = [
    {
        email: 'laura.sanchez@gmail.com',
        nombre: 'Laura Sánchez',
        telefono: '+34 612 345 678',
        totalReservas: 3,
        ultimaReserva: '2026-03-10',
        gastoTotal: 3150,
    },
    {
        email: 'ana.garcia@outlook.es',
        nombre: 'Ana García',
        telefono: '+34 655 987 321',
        totalReservas: 2,
        ultimaReserva: '2026-02-01',
        gastoTotal: 1820,
    },
    {
        email: 'miguel.torres@hotmail.com',
        nombre: 'Miguel Torres',
        telefono: '+34 698 123 456',
        totalReservas: 1,
        ultimaReserva: '2026-03-20',
        gastoTotal: 750,
    },
    {
        email: 'javier.lopez@icloud.com',
        nombre: 'Javier López',
        telefono: '+34 622 876 543',
        totalReservas: 4,
        ultimaReserva: '2026-04-15',
        gastoTotal: 4480,
    },
    {
        email: 'c.ruiz@empresa.com',
        nombre: 'Carlos Ruiz',
        telefono: '+34 607 654 321',
        totalReservas: 1,
        ultimaReserva: '2026-04-05',
        gastoTotal: 1190,
    },
    {
        email: 'isa.martinez@gmail.com',
        nombre: 'Isabel Martínez',
        telefono: '+34 633 111 222',
        totalReservas: 2,
        ultimaReserva: '2026-03-01',
        gastoTotal: 820,
    },
];

export const MOCK_VEHICULOS: AdminVehiculoEditable[] = [
    {
        id: 1,
        nombre: 'Cresta One',
        descripcionCorta: 'Furgoneta camper para 2 personas, totalmente equipada',
        capacidad: 2,
        plazasViaje: 2,
        combustible: 'diesel',
        transmision: 'manual',
        precioBase: 150,
        activo: true,
        ubicacion: 'Madrid',
        fianza: 500,
        kmIncluidos: 0,
        edadMinima: 21,
        equipamiento: ['cocina', 'nevera', 'ducha', 'panel solar', 'calefaccion'],
        imagen: '',
    },
];

export const MOCK_ACTIVIDAD: EventoActividad[] = [
    {
        tipo: 'entrega_hoy',
        mensaje: 'Entrega de Cresta One a Laura Sanchez',
        fecha: new Date().toISOString(),
        reservaId: 101,
        vehiculoNombre: 'Cresta One',
        clienteNombre: 'Laura Sanchez',
    },
    {
        tipo: 'reserva_confirmada',
        mensaje: 'Reserva #106 confirmada — Javier Lopez (1.120 EUR)',
        fecha: new Date(Date.now() - 3600000).toISOString(),
        reservaId: 106,
        vehiculoNombre: 'Cresta One',
        clienteNombre: 'Javier Lopez',
    },
    {
        tipo: 'nueva_reserva',
        mensaje: 'Nueva reserva #104 de Carlos Ruiz (pendiente de pago)',
        fecha: new Date(Date.now() - 7200000).toISOString(),
        reservaId: 104,
        vehiculoNombre: 'Cresta One',
        clienteNombre: 'Carlos Ruiz',
    },
    {
        tipo: 'devolucion_manana',
        mensaje: 'Devolucion de Cresta One manana — Ana Garcia',
        fecha: new Date(Date.now() - 14400000).toISOString(),
        reservaId: 103,
        vehiculoNombre: 'Cresta One',
        clienteNombre: 'Ana Garcia',
    },
    {
        tipo: 'reserva_cancelada',
        mensaje: 'Reserva #105 cancelada — Isabel Martinez',
        fecha: new Date(Date.now() - 86400000).toISOString(),
        reservaId: 105,
        vehiculoNombre: 'Cresta One',
        clienteNombre: 'Isabel Martinez',
    },
];
