<?php

use Glory\Manager\DefaultContentManager;

/*
 * Cresta Campers — Contenido por defecto
 * Vehículo semilla para desarrollo.
 */

DefaultContentManager::define('vehiculo', [
    [
        'slugDefault' => 'cresta-one',
        'titulo'      => 'Cresta One',        'imagenDestacadaAsset' => 'campers::cresta-one.jpg',        'contenido'   => 'Nuestra primera furgoneta camper, completamente equipada para tu aventura. Cocina, nevera, cama doble, calefacción estacionaria y mucho más. Perfecta para parejas o familias pequeñas que buscan libertad en la carretera.',
        'metaEntrada' => [
            '_vehiculo_nombre'               => 'Cresta One',
            '_vehiculo_descripcion_corta'     => 'Furgoneta camper equipada para 2 personas. Cocina, nevera, calefacción y todo lo que necesitas.',
            '_vehiculo_capacidad'             => 2,
            '_vehiculo_plazas_viaje'          => 4,
            '_vehiculo_combustible'           => 'diesel',
            '_vehiculo_transmision'           => 'manual',
            '_vehiculo_equipamiento'          => json_encode([
                'Cocina con fogón',
                'Nevera portátil',
                'Calefacción estacionaria',
                'Cama doble',
                'Mesa plegable',
                'Ducha exterior',
                'Toldo lateral',
                'Batería auxiliar',
                'Paneles solares',
                'Agua caliente',
            ]),
            '_vehiculo_galeria'               => '[]',
            '_vehiculo_precio_base'           => 89,
            '_vehiculo_activo'                => '1',
            '_vehiculo_ubicacion'             => 'Madrid',
            '_vehiculo_politica_cancelacion'  => 'estandar',
            '_vehiculo_fianza'                => 500,
            '_vehiculo_km_incluidos'          => 250,
            '_vehiculo_edad_minima'           => 21,
        ],
    ],
    [
        'slugDefault' => 'cresta-duo',
        'titulo'      => 'Cresta Duo',        'imagenDestacadaAsset' => 'campers::cresta-duo.jpg',        'contenido'   => 'La opción familiar de Cresta Campers. Con cuatro plazas para dormir, transmisión automática y el equipamiento más completo del catálogo, la Cresta Duo es perfecta para grupos y familias que no quieren renunciar a ninguna comodidad. Basada en un Volkswagen Crafter de gran capacidad, ofrece espacio para moverse con total libertad.',
        'metaEntrada' => [
            '_vehiculo_nombre'               => 'Cresta Duo',
            '_vehiculo_descripcion_corta'     => 'Camper familiar XL para 4 personas. Automática, cocina completa, literas y baño interior.',
            '_vehiculo_capacidad'             => 4,
            '_vehiculo_plazas_viaje'          => 5,
            '_vehiculo_combustible'           => 'diesel',
            '_vehiculo_transmision'           => 'automatico',
            '_vehiculo_equipamiento'          => json_encode([
                'Cocina de dos fogones',
                'Nevera compresor 60L',
                'Calefacción estacionaria Webasto',
                'Cama doble + literas traseras',
                'Mesa de comedor interior',
                'Ducha y baño interior',
                'Toldo lateral 3m',
                'Batería litio 200Ah',
                'Paneles solares 300W',
                'Agua caliente instantánea',
                'Portabicicletas trasero (2 bicis)',
                'Conexión eléctrica 220V',
            ]),
            '_vehiculo_galeria'               => '[]',
            '_vehiculo_precio_base'           => 129,
            '_vehiculo_activo'                => '1',
            '_vehiculo_ubicacion'             => 'Barcelona',
            '_vehiculo_politica_cancelacion'  => 'estandar',
            '_vehiculo_fianza'                => 700,
            '_vehiculo_km_incluidos'          => 300,
            '_vehiculo_edad_minima'           => 25,
        ],
    ],
    [
        'slugDefault' => 'cresta-pro',
        'titulo'      => 'Cresta Pro',        'imagenDestacadaAsset' => 'campers::cresta-pro.jpg',        'contenido'   => 'La experiencia premium de Cresta Campers. Basada en un Mercedes-Benz Sprinter de última generación, la Cresta Pro combina el tamaño compacto ideal para parejas con acabados de lujo: colchón viscoelástico, cocina de inducción, climatización independiente y sistema de entretenimiento integrado. Para quienes buscan la carretera sin renunciar al confort de un hotel.',
        'metaEntrada' => [
            '_vehiculo_nombre'               => 'Cresta Pro',
            '_vehiculo_descripcion_corta'     => 'Camper premium para 2 personas. Mercedes Sprinter con acabados de lujo, climatización y cocina de inducción.',
            '_vehiculo_capacidad'             => 2,
            '_vehiculo_plazas_viaje'          => 2,
            '_vehiculo_combustible'           => 'diesel',
            '_vehiculo_transmision'           => 'automatico',
            '_vehiculo_equipamiento'          => json_encode([
                'Cocina de inducción',
                'Nevera compresor 80L con congelador',
                'Climatización independiente',
                'Calefacción Webasto diesel',
                'Cama doble fija con colchón viscoelástico',
                'Baño con ducha y WC',
                'Toldo lateral eléctrico',
                'Batería litio 300Ah',
                'Paneles solares 400W',
                'Agua caliente y fría a presión',
                'TV 24" con antena satélite',
                'Conexión eléctrica 220V + USB',
                'Portabicicletas para 2 bicis',
                'Cámara de marcha atrás',
            ]),
            '_vehiculo_galeria'               => '[]',
            '_vehiculo_precio_base'           => 149,
            '_vehiculo_activo'                => '1',
            '_vehiculo_ubicacion'             => 'Sevilla',
            '_vehiculo_politica_cancelacion'  => 'flexible',
            '_vehiculo_fianza'                => 900,
            '_vehiculo_km_incluidos'          => 0,
            '_vehiculo_edad_minima'           => 23,
        ],
    ],
]);

