/*
 * Mock data de samples — Kamples
 * Datos de ejemplo para desarrollo local cuando la API aún no está disponible.
 * Se usan en InicioIsland, SamplesIsland, etc. como fallback.
 */

import type { SampleResumen, Sample } from '../types';

const creadorDemo = (id: number, username: string, nombre: string): SampleResumen['creador'] => ({
    id,
    username,
    nombreVisible: nombre,
    avatarUrl: null,
    verificado: id <= 3,
});

const c1 = creadorDemo(1, 'synthwave_king', 'Synthwave King');
const c2 = creadorDemo(2, 'lofi_beats', 'Lo-Fi Beats');
const c3 = creadorDemo(3, 'trap_nation', 'Trap Nation');
const c4 = creadorDemo(4, 'drumkit_pro', 'DrumKit Pro');
const c5 = creadorDemo(5, 'vocal_queen', 'Vocal Queen');

export const samplesMock: SampleResumen[] = [
    {
        id: 1,
        titulo: 'Midnight Synth Pad',
        slug: 'midnight-synth-pad',
        bpm: 128,
        key: 'D#',
        escala: 'menor',
        duracion: 8.2,
        tags: ['synth', 'ambient', 'pad', 'cinematic'],
        tipo: 'loop',
        esPremium: false,
        rutaPreview: '',
        rutaWaveform: '',
        imagenUrl: null,
        totalDescargas: 1240,
        totalLikes: 389,
        creador: c1,
    },
    {
        id: 2,
        titulo: '808 Hard Bounce',
        slug: '808-hard-bounce',
        bpm: 140,
        key: 'F',
        escala: 'menor',
        duracion: 4.0,
        tags: ['trap', '808', 'bass', 'hard'],
        tipo: 'oneshot',
        esPremium: false,
        rutaPreview: '',
        rutaWaveform: '',
        imagenUrl: null,
        totalDescargas: 3412,
        totalLikes: 872,
        creador: c3,
    },
    {
        id: 3,
        titulo: 'Dusty Vinyl Chords',
        slug: 'dusty-vinyl-chords',
        bpm: 85,
        key: 'A',
        escala: 'menor',
        duracion: 12.5,
        tags: ['lo-fi', 'piano', 'vinyl', 'chill'],
        tipo: 'loop',
        esPremium: true,
        rutaPreview: '',
        rutaWaveform: '',
        imagenUrl: null,
        totalDescargas: 567,
        totalLikes: 234,
        creador: c2,
    },
    {
        id: 4,
        titulo: 'Crystal Arp 130BPM',
        slug: 'crystal-arp-130bpm',
        bpm: 130,
        key: 'G',
        escala: 'mayor',
        duracion: 6.0,
        tags: ['synth', 'arp', 'future', 'bass'],
        tipo: 'loop',
        esPremium: false,
        rutaPreview: '',
        rutaWaveform: '',
        imagenUrl: null,
        totalDescargas: 890,
        totalLikes: 445,
        creador: c1,
    },
    {
        id: 5,
        titulo: 'Drill Hi-Hat Pattern',
        slug: 'drill-hihat-pattern',
        bpm: 145,
        key: null,
        escala: null,
        duracion: 4.0,
        tags: ['drill', 'hihat', 'drums', 'uk'],
        tipo: 'loop',
        esPremium: false,
        rutaPreview: '',
        rutaWaveform: '',
        imagenUrl: null,
        totalDescargas: 2100,
        totalLikes: 678,
        creador: c4,
    },
    {
        id: 6,
        titulo: 'Ethereal Vocal Chop',
        slug: 'ethereal-vocal-chop',
        bpm: 120,
        key: 'C',
        escala: 'mayor',
        duracion: 3.2,
        tags: ['vocal', 'chop', 'ethereal', 'pop'],
        tipo: 'vocal',
        esPremium: true,
        rutaPreview: '',
        rutaWaveform: '',
        imagenUrl: null,
        totalDescargas: 1890,
        totalLikes: 923,
        creador: c5,
    },
    {
        id: 7,
        titulo: 'Dark Piano Melody',
        slug: 'dark-piano-melody',
        bpm: 75,
        key: 'B',
        escala: 'menor',
        duracion: 16.0,
        tags: ['piano', 'dark', 'cinematic', 'emotional'],
        tipo: 'loop',
        esPremium: false,
        rutaPreview: '',
        rutaWaveform: '',
        imagenUrl: null,
        totalDescargas: 430,
        totalLikes: 198,
        creador: c2,
    },
    {
        id: 8,
        titulo: 'Reggaeton Perreo Base',
        slug: 'reggaeton-perreo-base',
        bpm: 95,
        key: 'E',
        escala: 'menor',
        duracion: 8.0,
        tags: ['reggaeton', 'perreo', 'latin', 'dembow'],
        tipo: 'loop',
        esPremium: false,
        rutaPreview: '',
        rutaWaveform: '',
        imagenUrl: null,
        totalDescargas: 5600,
        totalLikes: 1520,
        creador: c3,
    },
    {
        id: 9,
        titulo: 'Cinematic Riser FX',
        slug: 'cinematic-riser-fx',
        bpm: null,
        key: null,
        escala: null,
        duracion: 5.5,
        tags: ['fx', 'riser', 'cinematic', 'tension'],
        tipo: 'fx',
        esPremium: false,
        rutaPreview: '',
        rutaWaveform: '',
        imagenUrl: null,
        totalDescargas: 780,
        totalLikes: 312,
        creador: c4,
    },
    {
        id: 10,
        titulo: 'Phonk Cowbell Stack',
        slug: 'phonk-cowbell-stack',
        bpm: 130,
        key: null,
        escala: null,
        duracion: 2.0,
        tags: ['phonk', 'cowbell', 'drums', 'drift'],
        tipo: 'oneshot',
        esPremium: false,
        rutaPreview: '',
        rutaWaveform: '',
        imagenUrl: null,
        totalDescargas: 3200,
        totalLikes: 987,
        creador: c3,
    },
    {
        id: 11,
        titulo: 'House Groove Bassline',
        slug: 'house-groove-bassline',
        bpm: 124,
        key: 'F#',
        escala: 'menor',
        duracion: 8.0,
        tags: ['house', 'bass', 'groove', 'deep'],
        tipo: 'loop',
        esPremium: true,
        rutaPreview: '',
        rutaWaveform: '',
        imagenUrl: null,
        totalDescargas: 920,
        totalLikes: 456,
        creador: c1,
    },
    {
        id: 12,
        titulo: 'R&B Vocal Ad-lib Female',
        slug: 'rnb-vocal-adlib-female',
        bpm: 90,
        key: 'A',
        escala: 'mayor',
        duracion: 1.8,
        tags: ['r&b', 'vocal', 'adlib', 'female'],
        tipo: 'vocal',
        esPremium: false,
        rutaPreview: '',
        rutaWaveform: '',
        imagenUrl: null,
        totalDescargas: 2340,
        totalLikes: 780,
        creador: c5,
    },
];

/* Sample completo de detalle (para SampleDetalleIsland) */
export const sampleDetalladoMock: Sample = {
    id: 1,
    creadorId: 1,
    titulo: 'Midnight Synth Pad',
    slug: 'midnight-synth-pad',
    descripcion: 'Pad atmosférico con texturas analógicas. Perfecto para intros cinemáticas, ambientes dark wave o capas de fondo en producciones synthwave. Grabado con Prophet Rev2 + Strymon BigSky.',
    bpm: 128,
    key: 'D#',
    escala: 'menor',
    duracion: 8.2,
    formato: 'wav',
    tamano: 2450000,
    metadata: {
        genero: ['synthwave', 'ambient', 'cinematic'],
        instrumentos: ['synth', 'pad'],
        sentimiento: ['dark', 'atmospheric', 'dreamy'],
        tipo: 'loop',
        descripcionIA: 'Loop de pad sintetizado con carácter analógico, texturas warm y reverb larga.',
    },
    tags: ['synth', 'ambient', 'pad', 'cinematic'],
    estado: 'activo',
    esPremium: false,
    precio: null,
    rutaOriginal: '',
    rutaOptimizada: '',
    rutaPreview: '',
    rutaWaveform: '',
    imagenUrl: null,
    totalDescargas: 1240,
    totalLikes: 389,
    totalReproducciones: 4520,
    publicadoAt: '2026-02-10T14:30:00Z',
    creadoAt: '2026-02-10T14:00:00Z',
    actualizadoAt: '2026-02-14T09:00:00Z',
    creador: c1,
};

/* Subconjuntos pre-separados para las secciones del feed */
export const trendingMock = samplesMock.filter((_, i) => [1, 4, 7, 9, 5].includes(i)).slice(0, 5);
export const recientesMock = samplesMock.slice(6, 12);
export const descubrirMock = samplesMock.slice(0, 6);
